var myplaces = ["karachi", "UK", "sukkar", "hyderabad", "quetta"];
console.log(myplaces);
var copyofArray = myplaces.slice();
var sortedArray = copyofArray.sort();
console.log(sortedArray);
console.log(myplaces);
var copyofArray2 = myplaces.slice();
var reverseOriArray = (copyofArray2).reverse();
console.log(reverseOriArray);
console.log(myplaces);
var reverseOriArray2 = myplaces.reverse();
console.log(reverseOriArray2);
var sortOriArray = myplaces.sort();
console.log(sortOriArray);
var reversesortedArray = sortOriArray.reverse();
console.log(reversesortedArray);
